### ISSUE TITLE
smooth scrolling polyfill is broken on the new Safari 15.0 when combined with scroll-snapping

### ISSUE THREAD

**Issue by ivands** [JakeChampion/polyfill-service#2646]
The smooth scrolling polyfill is broken on the new Safari 15.0 on macOS and iOS when combined with scroll-snapping.
The expected behaviour is to scroll smoothly to a given point.
But with scroll-snap enabled the smoothness disappears. 

You can reproduce the bug easily by adding the following CSS to your scroll container:
```scroll-snap-type:inline mandatory;```

**Comment by bakura10** [comment]
Hi,

I raised this issue in the polyfill https://github.com/magic-akari/seamless-scroll-polyfill/issues/125

Unfortunately, after having done several tests myself, this is apparently won't fixable and is due to a change on how iOS15 scrollBy works in context of scroll-snapping.

The good news is that smooth scrolling has been enabled by default in Safari TP (so likely going to ship in iOS15.2 or iOS15.3) and that it works perfectly with the native feature :). So this one appears to be a non-fixable issue that will resolve by itself soon.
