### ISSUE TITLE
Security Vulnerability with internal dependency - growl v1.9.2

### ISSUE THREAD

**Issue by arpitgoyal2008** [JakeChampion/polyfill-service#2738]
Bug (Security Vulnerability Issue)

## What

[polyfill-service](https://www.npmjs.com/package/polyfill-service) latest version v3.25.3 uses growl v1.9.2 internally which has [critical security vulnerability](https://security.snyk.io/package/npm/growl/1.9.2). How can this be mitigated? Any help is greatly appreciated.

**Comment by JakeChampion** [comment]
Hi, we haven't published to npm for 4 years, this is because we extracted the library out from the service and expect people to use the library directly instead. The polyfill-service codebase itself no longer runs within NodeJS, it runs within Fastly's Compute@Edge platform.

The library can be found at https://www.npmjs.com/package/polyfill-library
